// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCSCPNE4j1MrLA2kbatg3epUzVgyX_3tJ0',
    appId: '1:806843890541:web:551123e9aec053e8f33864',
    messagingSenderId: '806843890541',
    projectId: 'cookmatch-858ae',
    authDomain: 'cookmatch-858ae.firebaseapp.com',
    databaseURL: 'https://cookmatch-858ae-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'cookmatch-858ae.firebasestorage.app',
    measurementId: 'G-FXKNKVGKYL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDK-a9V_ZiHz-eYgl9Hnkr_UjFWlbmkYJM',
    appId: '1:806843890541:android:bb40fce519df597af33864',
    messagingSenderId: '806843890541',
    projectId: 'cookmatch-858ae',
    databaseURL: 'https://cookmatch-858ae-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'cookmatch-858ae.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBFNCMzPuVijfCFaPST-sWNa7yEqq9T9lM',
    appId: '1:806843890541:ios:e6b4ea931f6b57f4f33864',
    messagingSenderId: '806843890541',
    projectId: 'cookmatch-858ae',
    databaseURL: 'https://cookmatch-858ae-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'cookmatch-858ae.firebasestorage.app',
    iosClientId: '806843890541-6lv5a20ngns3huk9dnv292hf80oj1l4s.apps.googleusercontent.com',
    iosBundleId: 'yegor.cheprasov.cookmatch',
  );
}
