library register;

import 'package:dartz/dartz.dart' show Either, left, right;
import 'package:equatable/equatable.dart';
import 'package:firebase_auth/firebase_auth.dart';
import 'package:flutter/material.dart';
import 'package:flutter_bloc/flutter_bloc.dart';
import 'package:gap/gap.dart';
import 'package:get_it/get_it.dart';
import 'package:go_router/go_router.dart';
import 'package:groceryhelper/app/router/app_router.dart';
import 'package:groceryhelper/infrastructure/services/locator.dart';
import 'package:groceryhelper/infrastructure/services/talker_service.dart';
import 'package:groceryhelper/shared/constants/app_assets.dart';
import 'package:groceryhelper/shared/constants/app_constant_values.dart';
import 'package:groceryhelper/shared/errors/errors.dart';
import 'package:groceryhelper/shared/validators/rule_validation_requirements_list.dart';
import 'package:groceryhelper/shared/validators/validators.dart';
import 'package:design/dialogs/state_dialog_manager.dart';
import 'package:design/design.dart';

part 'register_di.dart';
part 'presentation/screens/register_screen.dart';
part 'presentation/widgets/login_link.dart';
part 'presentation/bloc/register_bloc.dart';
part 'presentation/bloc/register_event.dart';
part 'presentation/bloc/register_state.dart';
part 'domain/entities/register_request.dart';
part 'domain/repositories/register_repository.dart';
part 'domain/usecases/register_usecase.dart';
part 'data/repositories/register_repository_factory.dart';
part 'data/repositories/register_repository_impl.dart';
part 'data/repositories/register_repository_mock.dart';
